language: python
env:
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34
install:
    - "pip install -r requirements.txt"
script:
    - "tox"
    # - "python setup.py test"
    
# http://borntyping.co.uk/posts/tox-and-travis-ci.html    
